site_name: Scripting Unix
nav:
  - Setup de l'environnement: 'index.md'
  - Shell:
    - Shell: 'shell/shell.md'
    - Cheatsheet Shell: 'shell/cheatsheet-shell.md'
  - Python:
    - Python: 'python.md'
    - Modularité: 'modularite.md'
    - Programmation orientée objet: 'python-oop.md'
  - Perl et Ruby: 'perl-ruby.md'
  - Awk et Expressions régulières:
    - Awk : 'awk.md'
    - Expressions régulières : 'regex.md'
  - Parallelisme en Shell et Python: 'parallelisme.md'
  - Travaux pratique: 'travaux-pratique.md'
  - Travaux pratique 2: 'travaux-pratique-simples.md'

# Theme material
theme:
  name: "material"
  language: "fr"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  icon:
    edit: fontawesome/regular/pen-to-square
    repo: simple/gitea
    annotation: material/eye-circle
  palette:
    scheme: slate
    primary: "cyan"
    accent: "cyan"
  features:
    - content.action.edit
    - search.highlight
    - search.suggest
    - navigation.top
    - content.code.copy
    # - navigation.sections
    # - navigation.indexes
    # - navigation.tracking
    # - navigation.path
  highlightjs: true
  hljs_languages:
    - yaml
    - django
    - nginx
    - console
    - properties
    - shell

# Extensions
markdown_extensions:
  - toc:
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins
plugins:
  - material/social:
      cards_layout: default/variant
      cards_layout_options:
        background_color: "#0b1329"
        font_family: VT323
  - search:
      separator: '[\s\-\.]+'
      lang:
        - fr

# Customization
extra_css:
  - stylesheets/extra.css
