# Generated by Django 5.1 on 2024-08-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('serveur', models.TextField()),
                ('criticity', models.TextField()),
                ('infogerant', models.TextField()),
                ('message', models.TextField()),
                ('application', models.TextField()),
                ('environnement', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
